apiVersion: v1
kind: ConfigMap
metadata:
  name: queue-handler-config
  namespace: test-mmp
data:
  application.yaml: |
    debug: false

    logging:
      config: file:logback.xml
      level:
        org:
          hibernate:
            SQL: TRACE
            type.descriptor.sql.BasicBinder: TRACE

    queue:
      config:
        host: mpay-rabbit.test-mmp.svc.cluster.local
        port: 5672
        heartbeat: 10
        username: ${RABBITMQ_USERNAME}
        password: ${RABBITMQ_PASSWORD}
        retry:
          interval: 10
        prefetch.count: 5
        auto.ack: false
        queue:
          request: AXIAN-WS-IN
          response: AXIAN-WS-OUT
        forwarders:
          from: AXIAN-WS-H-OUT
          to: AXIAN-WS-OUT
          prefetch.count: 3
          auto.ack: true
        request:
          forwarders:
            from: AXIAN-WS-H-IN
            to: NBPL-ISO-IN,NBPL-WS-H-IN,NBPL-1L-H-IN

    cache:
      name: requestCache
      expiry: 600000

    spring:
      mandatoryFileEncoding: UTF-8
      http:
        encoding:
          charset: UTF-8
          enabled: true
      datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        sqlScriptEncoding: UTF-8
        tomcat.connection-properties: useUnicode=yes;characterEncoding=utf-8;
        hikari:
          connection-test-query: SELECT 1
          minimum-idle: 8
          maximum-pool-size: 24
          pool-name: sql-pool
          auto-commit: true
          max-lifetime: 1800000
          leak-detection-threshold: 60000
      jpa:
        show-sql: true
        generate-ddl: false
        open-in-view: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
          ddl-auto: none
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
            id.new_generator_mappings: false
