# ── merchant-portal ─────────────────────────────────────────────────
name: merchant-portal
image: merchant-portal
port: 80
namespace: test-mmp
tag: 1.0.26
replicas: 1
host_alias_ip: 10.245.0.169
config_version: v1
rollout_timeout: 60
routing:
  prefix: /merchant-portal/
  rewrite: /
# scaling:
#   min: 2
#   max: 6
#   cpu_threshold: 70
#   mem_threshold: 80
secrets:
  - my-registry-secret
countries:
  tz:
    ambassador_host: mixxmmp-test.tigo.co.tz
    country: tz
    tls_secret: mixxmmp-tls-secret
    tag: 1.0.26
    previous_tag: 1.0.25
  tg:
    ambassador_host: togo.mixx.tg
    country: tg
    tls_secret: tg-tls
previous_tag: 1.0.25
